#!/bin/bash

DOCKER_IMAGE="linuxserver/ffmpeg:latest"

# Change working dir to the script folder
pushd "$(dirname "$0")" > /dev/null

tmp=$(dirname $(mktemp -u))

docker run -i --rm -v $tmp:$tmp ${DOCKER_IMAGE} "$@"
